# Verifies that libsearch links resolve properly. Takes a handle batch file 
# (e.g., generated by redirect_handle.rb) as input.

require 'net/http'

input_file = ARGV[0]
lines = File.readlines(input_file)
urls = lines.select { |line| line.include?("URL") }
            .map { |el| el.gsub(/\n/, '').split(' ') }
            .flatten
            .select { |el| el.include?('http') }
results = {}

urls.each do |url|
  response = Net::HTTP.get(URI.parse(url))

  # Check for response. Responses are actually bad in this case because it 
  # means SimpleSearch found an error.
  if response.length > 0
    results[url] = "Encountered errors"
  else
    results[url] = "No errors found"
  end
end

results.each { |k, v| puts "#{k}\t#{v}" }